# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/PositionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewPositionDialog(object):
    def setupUi(self, NewPositionDialog):
        NewPositionDialog.setObjectName("NewPositionDialog")
        NewPositionDialog.resize(587, 198)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewPositionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(NewPositionDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.manpowerEdit = QtWidgets.QLineEdit(NewPositionDialog)
        self.manpowerEdit.setObjectName("manpowerEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.manpowerEdit)
        self.label_2 = QtWidgets.QLabel(NewPositionDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.commanderCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.commanderCheck.setObjectName("commanderCheck")
        self.gridLayout.addWidget(self.commanderCheck, 0, 0, 1, 1)
        self.sharpshooterCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.sharpshooterCheck.setObjectName("sharpshooterCheck")
        self.gridLayout.addWidget(self.sharpshooterCheck, 0, 1, 1, 1)
        self.grenadeLauncherCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.grenadeLauncherCheck.setObjectName("grenadeLauncherCheck")
        self.gridLayout.addWidget(self.grenadeLauncherCheck, 0, 2, 1, 1)
        self.medicCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.medicCheck.setObjectName("medicCheck")
        self.gridLayout.addWidget(self.medicCheck, 1, 0, 1, 1)
        self.sniperCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.sniperCheck.setObjectName("sniperCheck")
        self.gridLayout.addWidget(self.sniperCheck, 1, 1, 1, 1)
        self.signallerCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.signallerCheck.setObjectName("signallerCheck")
        self.gridLayout.addWidget(self.signallerCheck, 1, 2, 1, 1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.label_3 = QtWidgets.QLabel(NewPositionDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.positionNameEdit = QtWidgets.QLineEdit(NewPositionDialog)
        self.positionNameEdit.setObjectName("positionNameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.positionNameEdit)
        self.label_4 = QtWidgets.QLabel(NewPositionDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox = QtWidgets.QCheckBox(NewPositionDialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 1, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(NewPositionDialog)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewPositionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(NewPositionDialog)
        self.buttonBox.accepted.connect(NewPositionDialog.accept)
        self.buttonBox.rejected.connect(NewPositionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewPositionDialog)
        NewPositionDialog.setTabOrder(self.positionNameEdit, self.manpowerEdit)
        NewPositionDialog.setTabOrder(self.manpowerEdit, self.commanderCheck)
        NewPositionDialog.setTabOrder(self.commanderCheck, self.sharpshooterCheck)
        NewPositionDialog.setTabOrder(self.sharpshooterCheck, self.grenadeLauncherCheck)
        NewPositionDialog.setTabOrder(self.grenadeLauncherCheck, self.medicCheck)
        NewPositionDialog.setTabOrder(self.medicCheck, self.sniperCheck)
        NewPositionDialog.setTabOrder(self.sniperCheck, self.signallerCheck)
        NewPositionDialog.setTabOrder(self.signallerCheck, self.checkBox)
        NewPositionDialog.setTabOrder(self.checkBox, self.checkBox_2)

    def retranslateUi(self, NewPositionDialog):
        _translate = QtCore.QCoreApplication.translate
        NewPositionDialog.setWindowTitle(_translate("NewPositionDialog", "Edit Position"))
        self.label.setText(_translate("NewPositionDialog", "Required Manpower"))
        self.label_2.setText(_translate("NewPositionDialog", "Requires"))
        self.commanderCheck.setText(_translate("NewPositionDialog", "Commander"))
        self.sharpshooterCheck.setText(_translate("NewPositionDialog", "Sharpshooter"))
        self.grenadeLauncherCheck.setText(_translate("NewPositionDialog", "Grenade Launcher"))
        self.medicCheck.setText(_translate("NewPositionDialog", "Medic"))
        self.sniperCheck.setText(_translate("NewPositionDialog", "Sniper"))
        self.signallerCheck.setText(_translate("NewPositionDialog", "Signaller"))
        self.label_3.setText(_translate("NewPositionDialog", "Position Name"))
        self.label_4.setText(_translate("NewPositionDialog", "Properties"))
        self.checkBox.setText(_translate("NewPositionDialog", "Mix Platoons"))
        self.checkBox_2.setText(_translate("NewPositionDialog", "Not Physical"))
