# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/PositionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewPositionDialog(object):
    def setupUi(self, NewPositionDialog):
        NewPositionDialog.setObjectName("NewPositionDialog")
        NewPositionDialog.setWindowModality(QtCore.Qt.WindowModal)
        NewPositionDialog.resize(587, 261)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewPositionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(NewPositionDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.uidEdit = QtWidgets.QLineEdit(NewPositionDialog)
        self.uidEdit.setText("")
        self.uidEdit.setReadOnly(True)
        self.uidEdit.setObjectName("uidEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.uidEdit)
        self.label_3 = QtWidgets.QLabel(NewPositionDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.positionNameEdit = QtWidgets.QLineEdit(NewPositionDialog)
        self.positionNameEdit.setObjectName("positionNameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.positionNameEdit)
        self.label = QtWidgets.QLabel(NewPositionDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.manpowerEdit = QtWidgets.QLineEdit(NewPositionDialog)
        self.manpowerEdit.setObjectName("manpowerEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.manpowerEdit)
        self.label_2 = QtWidgets.QLabel(NewPositionDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.rolesWidget = RolesWidget(NewPositionDialog)
        self.rolesWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rolesWidget.setObjectName("rolesWidget")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rolesWidget)
        self.label_4 = QtWidgets.QLabel(NewPositionDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.notPhysicalCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.notPhysicalCheck.setObjectName("notPhysicalCheck")
        self.gridLayout_2.addWidget(self.notPhysicalCheck, 1, 1, 1, 1)
        self.mixPlatoonsCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.mixPlatoonsCheck.setObjectName("mixPlatoonsCheck")
        self.gridLayout_2.addWidget(self.mixPlatoonsCheck, 1, 0, 1, 1)
        self.notCommanderCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.notCommanderCheck.setObjectName("notCommanderCheck")
        self.gridLayout_2.addWidget(self.notCommanderCheck, 2, 0, 1, 1)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        self.spacingNeededCheck = QtWidgets.QCheckBox(NewPositionDialog)
        self.spacingNeededCheck.setObjectName("spacingNeededCheck")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.spacingNeededCheck)
        self.widget = QtWidgets.QWidget(NewPositionDialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.spacingHourSpin = QtWidgets.QSpinBox(self.widget)
        self.spacingHourSpin.setObjectName("spacingHourSpin")
        self.horizontalLayout.addWidget(self.spacingHourSpin)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.spacingMinuteSpin = QtWidgets.QSpinBox(self.widget)
        self.spacingMinuteSpin.setObjectName("spacingMinuteSpin")
        self.horizontalLayout.addWidget(self.spacingMinuteSpin)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.widget)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewPositionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(NewPositionDialog)
        self.buttonBox.accepted.connect(NewPositionDialog.accept)
        self.buttonBox.rejected.connect(NewPositionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewPositionDialog)
        NewPositionDialog.setTabOrder(self.positionNameEdit, self.manpowerEdit)
        NewPositionDialog.setTabOrder(self.manpowerEdit, self.rolesWidget)
        NewPositionDialog.setTabOrder(self.rolesWidget, self.mixPlatoonsCheck)
        NewPositionDialog.setTabOrder(self.mixPlatoonsCheck, self.notPhysicalCheck)
        NewPositionDialog.setTabOrder(self.notPhysicalCheck, self.uidEdit)

    def retranslateUi(self, NewPositionDialog):
        _translate = QtCore.QCoreApplication.translate
        NewPositionDialog.setWindowTitle(_translate("NewPositionDialog", "עריכת עמדה"))
        self.label_5.setText(_translate("NewPositionDialog", "מזהה עמדה"))
        self.label_3.setText(_translate("NewPositionDialog", "שם העמדה"))
        self.label.setText(_translate("NewPositionDialog", "סד\"כ נדרש"))
        self.label_2.setText(_translate("NewPositionDialog", "בעלי תפקידים"))
        self.label_4.setText(_translate("NewPositionDialog", "מאפיינים"))
        self.notPhysicalCheck.setText(_translate("NewPositionDialog", "לא פיזי"))
        self.mixPlatoonsCheck.setText(_translate("NewPositionDialog", "ערבוב מחלקות"))
        self.notCommanderCheck.setText(_translate("NewPositionDialog", "לא מפקד"))
        self.spacingNeededCheck.setText(_translate("NewPositionDialog", "הפסקה דרושה"))
        self.label_6.setText(_translate("NewPositionDialog", "שעות"))
        self.label_7.setText(_translate("NewPositionDialog", "דקות"))
from Ui.Promoted.RolesWidget import RolesWidget
