# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/ShavzakWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Shavzak(object):
    def setupUi(self, Shavzak):
        Shavzak.setObjectName("Shavzak")
        Shavzak.resize(961, 635)
        self.centralwidget = QtWidgets.QWidget(Shavzak)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.manpowerView = QtWidgets.QTableView(self.centralwidget)
        self.manpowerView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.manpowerView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.manpowerView.setObjectName("manpowerView")
        self.manpowerView.horizontalHeader().setMinimumSectionSize(20)
        self.verticalLayout.addWidget(self.manpowerView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addSoldierButton = QtWidgets.QPushButton(self.centralwidget)
        self.addSoldierButton.setObjectName("addSoldierButton")
        self.horizontalLayout_2.addWidget(self.addSoldierButton)
        self.removeSoldierButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeSoldierButton.setEnabled(False)
        self.removeSoldierButton.setObjectName("removeSoldierButton")
        self.horizontalLayout_2.addWidget(self.removeSoldierButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.positionsView = QtWidgets.QTableView(self.centralwidget)
        self.positionsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.positionsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.positionsView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.positionsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.positionsView.setObjectName("positionsView")
        self.positionsView.horizontalHeader().setMinimumSectionSize(20)
        self.positionsView.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.positionsView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addPositionButton = QtWidgets.QPushButton(self.centralwidget)
        self.addPositionButton.setObjectName("addPositionButton")
        self.horizontalLayout_3.addWidget(self.addPositionButton)
        self.removePositionButton = QtWidgets.QPushButton(self.centralwidget)
        self.removePositionButton.setEnabled(False)
        self.removePositionButton.setObjectName("removePositionButton")
        self.horizontalLayout_3.addWidget(self.removePositionButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.shiftsView = QtWidgets.QTableView(self.centralwidget)
        self.shiftsView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.shiftsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.shiftsView.setObjectName("shiftsView")
        self.shiftsView.horizontalHeader().setMinimumSectionSize(20)
        self.shiftsView.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.shiftsView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addShiftButton = QtWidgets.QPushButton(self.centralwidget)
        self.addShiftButton.setEnabled(False)
        self.addShiftButton.setObjectName("addShiftButton")
        self.horizontalLayout_4.addWidget(self.addShiftButton)
        self.removeShiftButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeShiftButton.setEnabled(False)
        self.removeShiftButton.setObjectName("removeShiftButton")
        self.horizontalLayout_4.addWidget(self.removeShiftButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 112))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fromDateTime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.fromDateTime.setObjectName("fromDateTime")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fromDateTime)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.untilDateTime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.untilDateTime.setObjectName("untilDateTime")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.untilDateTime)
        self.horizontalLayout.addLayout(self.formLayout)
        self.generateButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateButton.sizePolicy().hasHeightForWidth())
        self.generateButton.setSizePolicy(sizePolicy)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout.addWidget(self.generateButton)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_4.addWidget(self.groupBox)
        Shavzak.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Shavzak)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Shavzak.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Shavzak)
        self.statusbar.setObjectName("statusbar")
        Shavzak.setStatusBar(self.statusbar)
        self.importAction = QtWidgets.QAction(Shavzak)
        self.importAction.setObjectName("importAction")
        self.exportAction = QtWidgets.QAction(Shavzak)
        self.exportAction.setObjectName("exportAction")
        self.importFromCsvAction = QtWidgets.QAction(Shavzak)
        self.importFromCsvAction.setObjectName("importFromCsvAction")
        self.menuFile.addAction(self.importAction)
        self.menuFile.addAction(self.exportAction)
        self.menuFile.addAction(self.importFromCsvAction)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Shavzak)
        self.addSoldierButton.clicked.connect(Shavzak.addSoldier)
        self.removeSoldierButton.clicked.connect(Shavzak.removeSoldier)
        self.addPositionButton.clicked.connect(Shavzak.addPosition)
        self.removePositionButton.clicked.connect(Shavzak.removePosition)
        self.addShiftButton.clicked.connect(Shavzak.addShift)
        self.removeShiftButton.clicked.connect(Shavzak.removeShift)
        self.positionsView.doubleClicked['QModelIndex'].connect(Shavzak.editPosition)
        self.shiftsView.doubleClicked['QModelIndex'].connect(Shavzak.editShift)
        self.importAction.triggered.connect(Shavzak.importData)
        self.exportAction.triggered.connect(Shavzak.exportData)
        self.manpowerView.doubleClicked['QModelIndex'].connect(Shavzak.editSoldier)
        self.importFromCsvAction.triggered.connect(Shavzak.importFromCsv)
        self.pushButton.clicked.connect(Shavzak.openCalendar)
        self.generateButton.clicked.connect(Shavzak.calculatePermutations)
        QtCore.QMetaObject.connectSlotsByName(Shavzak)
        Shavzak.setTabOrder(self.manpowerView, self.addSoldierButton)
        Shavzak.setTabOrder(self.addSoldierButton, self.removeSoldierButton)
        Shavzak.setTabOrder(self.removeSoldierButton, self.positionsView)
        Shavzak.setTabOrder(self.positionsView, self.addPositionButton)
        Shavzak.setTabOrder(self.addPositionButton, self.removePositionButton)
        Shavzak.setTabOrder(self.removePositionButton, self.shiftsView)
        Shavzak.setTabOrder(self.shiftsView, self.addShiftButton)
        Shavzak.setTabOrder(self.addShiftButton, self.removeShiftButton)
        Shavzak.setTabOrder(self.removeShiftButton, self.fromDateTime)
        Shavzak.setTabOrder(self.fromDateTime, self.untilDateTime)
        Shavzak.setTabOrder(self.untilDateTime, self.generateButton)
        Shavzak.setTabOrder(self.generateButton, self.pushButton)

    def retranslateUi(self, Shavzak):
        _translate = QtCore.QCoreApplication.translate
        Shavzak.setWindowTitle(_translate("Shavzak", "ניהול מוצב"))
        self.label.setText(_translate("Shavzak", "כוח אדם"))
        self.addSoldierButton.setText(_translate("Shavzak", "הוסף"))
        self.removeSoldierButton.setText(_translate("Shavzak", "הסר"))
        self.label_2.setText(_translate("Shavzak", "עמדות"))
        self.addPositionButton.setText(_translate("Shavzak", "הוסף"))
        self.removePositionButton.setText(_translate("Shavzak", "הסר"))
        self.label_3.setText(_translate("Shavzak", "משמרות"))
        self.addShiftButton.setText(_translate("Shavzak", "הוסף"))
        self.removeShiftButton.setText(_translate("Shavzak", "הסר"))
        self.groupBox.setTitle(_translate("Shavzak", "פרמוטטור"))
        self.label_4.setText(_translate("Shavzak", "זמן התחלה"))
        self.fromDateTime.setDisplayFormat(_translate("Shavzak", "d/M/yyyy hh:mm"))
        self.label_5.setText(_translate("Shavzak", "זמן סיום"))
        self.untilDateTime.setDisplayFormat(_translate("Shavzak", "d/M/yyyy hh:mm"))
        self.generateButton.setText(_translate("Shavzak", "ייצר"))
        self.pushButton.setText(_translate("Shavzak", "פתח שיבוץ קרבי"))
        self.menuFile.setTitle(_translate("Shavzak", "קובץ"))
        self.importAction.setText(_translate("Shavzak", "טען נתונים מקובץ"))
        self.exportAction.setText(_translate("Shavzak", "שמור נתונים לקובץ"))
        self.importFromCsvAction.setText(_translate("Shavzak", "טען מקובץ CSV"))
