# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/ShiftDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShiftDialog(object):
    def setupUi(self, ShiftDialog):
        ShiftDialog.setObjectName("ShiftDialog")
        ShiftDialog.setWindowModality(QtCore.Qt.WindowModal)
        ShiftDialog.resize(496, 390)
        self.formLayout = QtWidgets.QFormLayout(ShiftDialog)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(ShiftDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.positionCombo = QtWidgets.QComboBox(ShiftDialog)
        self.positionCombo.setObjectName("positionCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.positionCombo)
        self.label_11 = QtWidgets.QLabel(ShiftDialog)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.nicknameEdit = QtWidgets.QLineEdit(ShiftDialog)
        self.nicknameEdit.setObjectName("nicknameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nicknameEdit)
        self.label = QtWidgets.QLabel(ShiftDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.widget = QtWidgets.QWidget(ShiftDialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sundayCheck = QtWidgets.QCheckBox(self.widget)
        self.sundayCheck.setChecked(True)
        self.sundayCheck.setObjectName("sundayCheck")
        self.gridLayout.addWidget(self.sundayCheck, 0, 0, 1, 1)
        self.mondayCheck = QtWidgets.QCheckBox(self.widget)
        self.mondayCheck.setChecked(True)
        self.mondayCheck.setObjectName("mondayCheck")
        self.gridLayout.addWidget(self.mondayCheck, 0, 1, 1, 1)
        self.tuesdayCheck = QtWidgets.QCheckBox(self.widget)
        self.tuesdayCheck.setChecked(True)
        self.tuesdayCheck.setObjectName("tuesdayCheck")
        self.gridLayout.addWidget(self.tuesdayCheck, 0, 2, 1, 1)
        self.wednesdayCheck = QtWidgets.QCheckBox(self.widget)
        self.wednesdayCheck.setChecked(True)
        self.wednesdayCheck.setObjectName("wednesdayCheck")
        self.gridLayout.addWidget(self.wednesdayCheck, 1, 0, 1, 1)
        self.thursdayCheck = QtWidgets.QCheckBox(self.widget)
        self.thursdayCheck.setChecked(True)
        self.thursdayCheck.setObjectName("thursdayCheck")
        self.gridLayout.addWidget(self.thursdayCheck, 1, 1, 1, 1)
        self.fridayCheck = QtWidgets.QCheckBox(self.widget)
        self.fridayCheck.setChecked(True)
        self.fridayCheck.setObjectName("fridayCheck")
        self.gridLayout.addWidget(self.fridayCheck, 1, 2, 1, 1)
        self.saturdayCheck = QtWidgets.QCheckBox(self.widget)
        self.saturdayCheck.setChecked(True)
        self.saturdayCheck.setObjectName("saturdayCheck")
        self.gridLayout.addWidget(self.saturdayCheck, 2, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.widget)
        self.label_2 = QtWidgets.QLabel(ShiftDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fromTime = QtWidgets.QTimeEdit(ShiftDialog)
        self.fromTime.setObjectName("fromTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fromTime)
        self.label_3 = QtWidgets.QLabel(ShiftDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(ShiftDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.durationHourSpin = QtWidgets.QSpinBox(ShiftDialog)
        self.durationHourSpin.setObjectName("durationHourSpin")
        self.horizontalLayout.addWidget(self.durationHourSpin)
        self.label_6 = QtWidgets.QLabel(ShiftDialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.durationMinuteSpin = QtWidgets.QSpinBox(ShiftDialog)
        self.durationMinuteSpin.setMaximum(59)
        self.durationMinuteSpin.setObjectName("durationMinuteSpin")
        self.horizontalLayout.addWidget(self.durationMinuteSpin)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_7 = QtWidgets.QLabel(ShiftDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.stickToShiftCombo = QtWidgets.QComboBox(ShiftDialog)
        self.stickToShiftCombo.setObjectName("stickToShiftCombo")
        self.stickToShiftCombo.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.stickToShiftCombo)
        self.label_8 = QtWidgets.QLabel(ShiftDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.validFromDatetime = QtWidgets.QDateTimeEdit(ShiftDialog)
        self.validFromDatetime.setObjectName("validFromDatetime")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.validFromDatetime)
        self.validUntilCheck = QtWidgets.QCheckBox(ShiftDialog)
        self.validUntilCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.validUntilCheck.setObjectName("validUntilCheck")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.validUntilCheck)
        self.validUntilDatetime = QtWidgets.QDateTimeEdit(ShiftDialog)
        self.validUntilDatetime.setEnabled(False)
        self.validUntilDatetime.setObjectName("validUntilDatetime")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.validUntilDatetime)
        self.splitShiftCheck = QtWidgets.QCheckBox(ShiftDialog)
        self.splitShiftCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.splitShiftCheck.setObjectName("splitShiftCheck")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.splitShiftCheck)
        self.splitShiftSpin = QtWidgets.QSpinBox(ShiftDialog)
        self.splitShiftSpin.setMaximum(1000)
        self.splitShiftSpin.setObjectName("splitShiftSpin")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.splitShiftSpin)
        self.buttonBox = QtWidgets.QDialogButtonBox(ShiftDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(ShiftDialog)
        self.buttonBox.accepted.connect(ShiftDialog.accept)
        self.buttonBox.rejected.connect(ShiftDialog.reject)
        self.validUntilCheck.toggled['bool'].connect(self.validUntilDatetime.setEnabled)
        self.splitShiftCheck.toggled['bool'].connect(self.widget.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(ShiftDialog)
        ShiftDialog.setTabOrder(self.positionCombo, self.nicknameEdit)
        ShiftDialog.setTabOrder(self.nicknameEdit, self.fromTime)
        ShiftDialog.setTabOrder(self.fromTime, self.durationHourSpin)
        ShiftDialog.setTabOrder(self.durationHourSpin, self.durationMinuteSpin)
        ShiftDialog.setTabOrder(self.durationMinuteSpin, self.stickToShiftCombo)
        ShiftDialog.setTabOrder(self.stickToShiftCombo, self.validFromDatetime)
        ShiftDialog.setTabOrder(self.validFromDatetime, self.validUntilCheck)
        ShiftDialog.setTabOrder(self.validUntilCheck, self.validUntilDatetime)
        ShiftDialog.setTabOrder(self.validUntilDatetime, self.splitShiftCheck)
        ShiftDialog.setTabOrder(self.splitShiftCheck, self.splitShiftSpin)

    def retranslateUi(self, ShiftDialog):
        _translate = QtCore.QCoreApplication.translate
        ShiftDialog.setWindowTitle(_translate("ShiftDialog", "עריכת משמרת"))
        self.label_4.setText(_translate("ShiftDialog", "עמדה"))
        self.label_11.setText(_translate("ShiftDialog", "כינוי משמרת"))
        self.label.setText(_translate("ShiftDialog", "ימים"))
        self.sundayCheck.setText(_translate("ShiftDialog", "ראשון"))
        self.mondayCheck.setText(_translate("ShiftDialog", "שני"))
        self.tuesdayCheck.setText(_translate("ShiftDialog", "שלישי"))
        self.wednesdayCheck.setText(_translate("ShiftDialog", "רביעי"))
        self.thursdayCheck.setText(_translate("ShiftDialog", "חמישי"))
        self.fridayCheck.setText(_translate("ShiftDialog", "שישי"))
        self.saturdayCheck.setText(_translate("ShiftDialog", "שבת"))
        self.label_2.setText(_translate("ShiftDialog", "שעת התחלה"))
        self.fromTime.setDisplayFormat(_translate("ShiftDialog", "hh:mm"))
        self.label_3.setText(_translate("ShiftDialog", "זמן משמרת"))
        self.label_5.setText(_translate("ShiftDialog", "שעות"))
        self.label_6.setText(_translate("ShiftDialog", "דקות"))
        self.label_7.setText(_translate("ShiftDialog", "הצמד למשמרת"))
        self.stickToShiftCombo.setItemText(0, _translate("ShiftDialog", "ללא הצמדה"))
        self.label_8.setText(_translate("ShiftDialog", "החל מ-"))
        self.validFromDatetime.setDisplayFormat(_translate("ShiftDialog", "d/M/yy hh:mm"))
        self.validUntilCheck.setText(_translate("ShiftDialog", "עד ל-"))
        self.validUntilDatetime.setDisplayFormat(_translate("ShiftDialog", "d/M/yy hh:mm"))
        self.splitShiftCheck.setText(_translate("ShiftDialog", "פצל משמרת"))
