# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/SoldierDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SoldierDialog(object):
    def setupUi(self, SoldierDialog):
        SoldierDialog.setObjectName("SoldierDialog")
        SoldierDialog.resize(623, 365)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SoldierDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SoldierDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.soldierNameEdit = QtWidgets.QLineEdit(SoldierDialog)
        self.soldierNameEdit.setObjectName("soldierNameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.soldierNameEdit)
        self.label_2 = QtWidgets.QLabel(SoldierDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.platoonCombo = QtWidgets.QComboBox(SoldierDialog)
        self.platoonCombo.setObjectName("platoonCombo")
        self.platoonCombo.addItem("")
        self.platoonCombo.addItem("")
        self.platoonCombo.addItem("")
        self.platoonCombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.platoonCombo)
        self.label_3 = QtWidgets.QLabel(SoldierDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sharpshooterCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.sharpshooterCheck.setObjectName("sharpshooterCheck")
        self.gridLayout.addWidget(self.sharpshooterCheck, 0, 2, 1, 1)
        self.grenLauncherCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.grenLauncherCheck.setObjectName("grenLauncherCheck")
        self.gridLayout.addWidget(self.grenLauncherCheck, 0, 3, 1, 1)
        self.commanderCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.commanderCheck.setObjectName("commanderCheck")
        self.gridLayout.addWidget(self.commanderCheck, 0, 1, 1, 1)
        self.officerCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.officerCheck.setObjectName("officerCheck")
        self.gridLayout.addWidget(self.officerCheck, 0, 0, 1, 1)
        self.medicCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.medicCheck.setObjectName("medicCheck")
        self.gridLayout.addWidget(self.medicCheck, 1, 0, 1, 1)
        self.sniperCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.sniperCheck.setObjectName("sniperCheck")
        self.gridLayout.addWidget(self.sniperCheck, 1, 1, 1, 1)
        self.signallerCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.signallerCheck.setObjectName("signallerCheck")
        self.gridLayout.addWidget(self.signallerCheck, 1, 2, 1, 1)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.label_4 = QtWidgets.QLabel(SoldierDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(SoldierDialog)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(SoldierDialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(SoldierDialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.label_5 = QtWidgets.QLabel(SoldierDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pnEdit = QtWidgets.QLineEdit(SoldierDialog)
        self.pnEdit.setObjectName("pnEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pnEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(SoldierDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(SoldierDialog)
        self.buttonBox.accepted.connect(SoldierDialog.accept)
        self.buttonBox.rejected.connect(SoldierDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SoldierDialog)
        SoldierDialog.setTabOrder(self.pnEdit, self.soldierNameEdit)
        SoldierDialog.setTabOrder(self.soldierNameEdit, self.platoonCombo)
        SoldierDialog.setTabOrder(self.platoonCombo, self.officerCheck)
        SoldierDialog.setTabOrder(self.officerCheck, self.commanderCheck)
        SoldierDialog.setTabOrder(self.commanderCheck, self.sharpshooterCheck)
        SoldierDialog.setTabOrder(self.sharpshooterCheck, self.grenLauncherCheck)
        SoldierDialog.setTabOrder(self.grenLauncherCheck, self.medicCheck)
        SoldierDialog.setTabOrder(self.medicCheck, self.sniperCheck)
        SoldierDialog.setTabOrder(self.sniperCheck, self.signallerCheck)
        SoldierDialog.setTabOrder(self.signallerCheck, self.listWidget)
        SoldierDialog.setTabOrder(self.listWidget, self.pushButton)
        SoldierDialog.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, SoldierDialog):
        _translate = QtCore.QCoreApplication.translate
        SoldierDialog.setWindowTitle(_translate("SoldierDialog", "Edit Soldier"))
        self.label.setText(_translate("SoldierDialog", "Soldier name"))
        self.label_2.setText(_translate("SoldierDialog", "Platoon"))
        self.platoonCombo.setItemText(0, _translate("SoldierDialog", "1"))
        self.platoonCombo.setItemText(1, _translate("SoldierDialog", "2"))
        self.platoonCombo.setItemText(2, _translate("SoldierDialog", "3"))
        self.platoonCombo.setItemText(3, _translate("SoldierDialog", "Maflag"))
        self.label_3.setText(_translate("SoldierDialog", "Role"))
        self.sharpshooterCheck.setText(_translate("SoldierDialog", "Sharpshooter"))
        self.grenLauncherCheck.setText(_translate("SoldierDialog", "Grenade Launcher"))
        self.commanderCheck.setText(_translate("SoldierDialog", "Commander"))
        self.officerCheck.setText(_translate("SoldierDialog", "Officer / Sgt."))
        self.medicCheck.setText(_translate("SoldierDialog", "Medic"))
        self.sniperCheck.setText(_translate("SoldierDialog", "Sniper"))
        self.signallerCheck.setText(_translate("SoldierDialog", "Signaller"))
        self.label_4.setText(_translate("SoldierDialog", "Absences"))
        self.pushButton.setText(_translate("SoldierDialog", "Add Absence"))
        self.pushButton_2.setText(_translate("SoldierDialog", "Remove Absence"))
        self.label_5.setText(_translate("SoldierDialog", "P.N"))
