# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/SoldierDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SoldierDialog(object):
    def setupUi(self, SoldierDialog):
        SoldierDialog.setObjectName("SoldierDialog")
        SoldierDialog.resize(623, 373)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SoldierDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SoldierDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.soldierNameEdit = QtWidgets.QLineEdit(SoldierDialog)
        self.soldierNameEdit.setObjectName("soldierNameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.soldierNameEdit)
        self.label_2 = QtWidgets.QLabel(SoldierDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.platoonCombo = QtWidgets.QComboBox(SoldierDialog)
        self.platoonCombo.setObjectName("platoonCombo")
        self.platoonCombo.addItem("")
        self.platoonCombo.addItem("")
        self.platoonCombo.addItem("")
        self.platoonCombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.platoonCombo)
        self.label_3 = QtWidgets.QLabel(SoldierDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.commanderCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.commanderCheck.setObjectName("commanderCheck")
        self.gridLayout.addWidget(self.commanderCheck, 0, 1, 1, 1)
        self.sharpshooterCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.sharpshooterCheck.setObjectName("sharpshooterCheck")
        self.gridLayout.addWidget(self.sharpshooterCheck, 0, 2, 1, 1)
        self.medicCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.medicCheck.setObjectName("medicCheck")
        self.gridLayout.addWidget(self.medicCheck, 1, 0, 1, 1)
        self.officerCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.officerCheck.setObjectName("officerCheck")
        self.gridLayout.addWidget(self.officerCheck, 0, 0, 1, 1)
        self.signallerCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.signallerCheck.setObjectName("signallerCheck")
        self.gridLayout.addWidget(self.signallerCheck, 1, 2, 1, 1)
        self.grenLauncherCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.grenLauncherCheck.setObjectName("grenLauncherCheck")
        self.gridLayout.addWidget(self.grenLauncherCheck, 0, 3, 1, 1)
        self.sniperCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.sniperCheck.setObjectName("sniperCheck")
        self.gridLayout.addWidget(self.sniperCheck, 1, 1, 1, 1)
        self.hamalistCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.hamalistCheck.setObjectName("hamalistCheck")
        self.gridLayout.addWidget(self.hamalistCheck, 1, 3, 1, 1)
        self.hamalRunnerCheck = QtWidgets.QCheckBox(SoldierDialog)
        self.hamalRunnerCheck.setObjectName("hamalRunnerCheck")
        self.gridLayout.addWidget(self.hamalRunnerCheck, 2, 0, 1, 1)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.label_4 = QtWidgets.QLabel(SoldierDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(SoldierDialog)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addAbsenceButton = QtWidgets.QPushButton(SoldierDialog)
        self.addAbsenceButton.setObjectName("addAbsenceButton")
        self.horizontalLayout.addWidget(self.addAbsenceButton)
        self.removeAbsenceButton = QtWidgets.QPushButton(SoldierDialog)
        self.removeAbsenceButton.setObjectName("removeAbsenceButton")
        self.horizontalLayout.addWidget(self.removeAbsenceButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.label_5 = QtWidgets.QLabel(SoldierDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pnEdit = QtWidgets.QLineEdit(SoldierDialog)
        self.pnEdit.setObjectName("pnEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pnEdit)
        self.label_6 = QtWidgets.QLabel(SoldierDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.telephoneEdit = QtWidgets.QLineEdit(SoldierDialog)
        self.telephoneEdit.setObjectName("telephoneEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.telephoneEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(SoldierDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(SoldierDialog)
        self.buttonBox.accepted.connect(SoldierDialog.accept)
        self.buttonBox.rejected.connect(SoldierDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SoldierDialog)
        SoldierDialog.setTabOrder(self.pnEdit, self.soldierNameEdit)
        SoldierDialog.setTabOrder(self.soldierNameEdit, self.platoonCombo)
        SoldierDialog.setTabOrder(self.platoonCombo, self.telephoneEdit)
        SoldierDialog.setTabOrder(self.telephoneEdit, self.officerCheck)
        SoldierDialog.setTabOrder(self.officerCheck, self.commanderCheck)
        SoldierDialog.setTabOrder(self.commanderCheck, self.sharpshooterCheck)
        SoldierDialog.setTabOrder(self.sharpshooterCheck, self.grenLauncherCheck)
        SoldierDialog.setTabOrder(self.grenLauncherCheck, self.medicCheck)
        SoldierDialog.setTabOrder(self.medicCheck, self.sniperCheck)
        SoldierDialog.setTabOrder(self.sniperCheck, self.signallerCheck)
        SoldierDialog.setTabOrder(self.signallerCheck, self.listWidget)
        SoldierDialog.setTabOrder(self.listWidget, self.addAbsenceButton)
        SoldierDialog.setTabOrder(self.addAbsenceButton, self.removeAbsenceButton)
        SoldierDialog.setTabOrder(self.removeAbsenceButton, self.hamalistCheck)
        SoldierDialog.setTabOrder(self.hamalistCheck, self.hamalRunnerCheck)

    def retranslateUi(self, SoldierDialog):
        _translate = QtCore.QCoreApplication.translate
        SoldierDialog.setWindowTitle(_translate("SoldierDialog", "עריכת חייל"))
        self.label.setText(_translate("SoldierDialog", "שם החייל"))
        self.label_2.setText(_translate("SoldierDialog", "מחלקה"))
        self.platoonCombo.setItemText(0, _translate("SoldierDialog", "1"))
        self.platoonCombo.setItemText(1, _translate("SoldierDialog", "2"))
        self.platoonCombo.setItemText(2, _translate("SoldierDialog", "3"))
        self.platoonCombo.setItemText(3, _translate("SoldierDialog", "מפל\"ג"))
        self.label_3.setText(_translate("SoldierDialog", "תפקיד"))
        self.commanderCheck.setText(_translate("SoldierDialog", "מפקד"))
        self.sharpshooterCheck.setText(_translate("SoldierDialog", "קלע"))
        self.medicCheck.setText(_translate("SoldierDialog", "חובש"))
        self.officerCheck.setText(_translate("SoldierDialog", "מ\"מ / סמל"))
        self.signallerCheck.setText(_translate("SoldierDialog", "קשר"))
        self.grenLauncherCheck.setText(_translate("SoldierDialog", "מטול"))
        self.sniperCheck.setText(_translate("SoldierDialog", "צלף"))
        self.hamalistCheck.setText(_translate("SoldierDialog", "חמ\"ליסט"))
        self.hamalRunnerCheck.setText(_translate("SoldierDialog", "רץ חמ\"ל"))
        self.label_4.setText(_translate("SoldierDialog", "היעדרויות"))
        self.addAbsenceButton.setText(_translate("SoldierDialog", "הוסיף היעדרות"))
        self.removeAbsenceButton.setText(_translate("SoldierDialog", "הסר היעדרות"))
        self.label_5.setText(_translate("SoldierDialog", "מ.א"))
        self.label_6.setText(_translate("SoldierDialog", "מספר טלפון"))
